imageRegistry: "545931885961.dkr.ecr.ap-south-1.amazonaws.com"

services:
  auth:
    image: streaming-auth
    tag: "1.0.1"
    port: 3001
  stream:
    image: streaming-stream
    tag: "1.0.1"
    port: 3002
  admin:
    image: streaming-admin
    tag: "1.0.1"
    port: 3003
  chat:
    image: streaming-chat
    tag: "1.0.1"
    port: 3004
  frontend:
    image: streaming-frontend
    tag: "1.0.2"
    port: 80

mongodb:
  image: mongo:7
  port: 27017
  database: streamingapp

frontend:
  serviceType: LoadBalancer

  allowedOrigin: "http://a724b80962ea041409ffaaf475a72517-1001878487.ap-south-1.elb.amazonaws.com"
