apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: streaming-mongodb-data
  namespace: streamingapp
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: streamingapp-gp3
  resources:
    requests:
      storage: 10Gi
